[tools]
node = "22.21"
yarn = "4.10.3"
python = '3.14.0'
poetry = '1.8.5'
"http:ldcli" = { version = "2.0.1", url = "https://github.com/launchdarkly/ldcli/releases/download/v{{version}}/ldcli_{{version}}_linux_amd64.tar.gz" }
